name: SMS Cron

on:
  schedule:
    - cron: '* * * * *'

jobs:
  send-sms:
    runs-on: ubuntu-latest
    steps:
      - name: Call SMS API
        run: |
          curl https://sparkly-madeleine-5f03bc.netlify.app/api/send-sms